main_args:
  is_train: True
  use_all_data: True
  all_img_path: "data/PGDP5K/all_img"
  dataset_name: "PGDP5K"
  project_name: "v2.4_train_rel"
  backbone_weights: "https://cloudstor.aarnet.edu.au/plus/s/xtixKaxLWmbcyf7/download#mobilenet_v2-ecbe2b5.pth"
  resume: "archie_west_best/best.pth"
  save_dir: "checkpoints"
  train_annot_path: "data/PGDP5K/annotations/train_revised.json"
  eval_annot_path: "data/PGDP5K/annotations/val_revised.json"
  test_annot_path: "data/PGDP5K/annotations/test_revised.json"
  train_img_path: "data/PGDP5K/train"
  eval_img_path: "data/PGDP5K/val"
  test_img_path: "data/PGDP5K/test"
  aspect_ratio_group_factor: 3
  train_img_per_batch: 20
  test_img_per_batch: 20
  workers: 8
  dist_url: "env://"
  sync_bn: True
  amp: False
  print_freq: 1
  seed: 42
  device: "cuda"
  # wandb_key: "e4585419c5dac8004748c8f4ea34d6d4faeb64e2"
  wandb_key: null
  epochs: 100
  warmpup: False
  toy_data: False
  #  only_train_rel  only_parse
  #    True           True     >> invalid
  #    True           False    >> fix seg_det, train rel
  #    False          True     >> train seg_det, no rel
  #    False          False    >> normal 
  only_train_rel: True
  only_parse: False
optimizer_args:
  optimization_method: "sgd"
  momentum: 0.9
  weight_decay: 0.0005
  weight_decay_bias: 0
  lr: 1.0e-5
  bias_factor: 2
  lr_steps: [5, 10, 15]
  lr_gamma: 0.2
image_input:
  min_size_train: [900, 700, 500]
  max_size_train: 1200
  min_size_test: 700
  max_size_test: 1200
backbone_args:
  freeze_conv_body_at: 0
  backbone_out_channels: 128
  fpn_use_gn: False
  fpn_use_relu: False
  fpn_strides: [8, 16, 32, 64, 128]
rpn_args:
  rpn_num_classes: 18
  rpn_num_convs: 3
  rpn_norm_reg_targets: False
  rpn_centerness_on_reg: False
  rpn_use_dcn_in_tower: False
  rpn_inference_th: 0.2
  rpn_pre_nms_top_n: 1000
  rpn_nms_th: 0.5
  rpn_det_per_img: 100
  rpn_bbox_aug_enabled: False
  rpn_center_sampling_radius: 0.0
  rpn_iou_loss_type: "iou"
seg_args:
  seg_num_classes: 4
  seg_emb_dims: 8
  seg_num_convs: 3
  seg_fpn_strides: 4
  loss_ratio_bs: 4.0
  loss_ratio_var: 4.0
  loss_ratio_dist: 4.0
  loss_ratio_reg: 0.0
visemb_args:
  vis_emb_dims: 64
  vis_num_convs: 3
sym_args:
  sym_roi_output_size: 3
  sym_embed_size: 64
geo_args:
  geo_embed_size: 64
rel_args:
  geo_rel_size: 64
  sym_rel_size: 64
  weak_mask: 0.55
  threshold: 0.5
solution_generation_data_args:
  t5_train_img_per_batch: 8
  t5_test_img_per_batch: 8
  t5_train_img_path: "data/UniGeo/images_unigeo_cal"
  t5_eval_img_path: "data/UniGeo/images_unigeo_cal"
  t5_test_img_path: "data/UniGeo/images_unigeo_cal"
  t5_train_annot_path: "data/UniGeo/UniGeo_CAL_train.json" 
  t5_eval_annot_path: "data/UniGeo/UniGeo_CAL_val.json" 
  t5_test_annot_path: "data/UniGeo/UniGeo_CAL_test.json"
  t5_train_parse_path: "data/UniGeo/UniGeo_CAL_parse_train.json"
  t5_eval_parse_path: "data/UniGeo/UniGeo_CAL_parse_val.json"
  t5_test_parse_path: "data/UniGeo/UniGeo_CAL_parse_test.json"
  problem_form: "calculation"
solution_generation_model_args:
  gp_resume: null
  model_type: "t5-base"
  beam_size: 1
  t5_lr: 1.0e-4
  adam_eps: 1.0e-6
test_args:
  enable_geo_rel: True
  